# Site settings
baseurl = "https://RiverbankCounselling.com/"
canonifyurls = true
relativeurls = false
languageCode = "en-us"
title = "Riverbank Counselling"
theme = "freelancer"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

    name = "Riverbank Counselling"
    description = "????????????"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "otexts@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = ""

    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "riverbank3.jpg"
        name = "Riverbank Counselling"
        subtitle = "Individual and group counselling for children."

    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Riverbank Counselling provides low cost individual and group counselling for students at Lilydale West Primary School.<p>**Leanne Hyndman** has a Bachelor of Arts in Counselling from Tabor College and a Masters of Narrative Therapy & Community Work from the University of Melbourne."
        right = "**Individual Counselling:** $260. Includes 5 sessions (45mins), primary caregiver intake conversation, teacher communication (if desired).<br> **Follow-up Sessions:** $90. This is only for students who have had a group of 5 sessions and who may need to have a couple of check in sessions each term.  Includes 90 mins of counselling time used as needed."

    [params.details]
        title = "Details"
        left = "**Values:** I aim to work with children in a way that helps them to find their own skills to help with problems or hard times.  I intend to honour different family structures and practices without judgement.<p>I am particularly trained in two forms of counselling that are often used when working with children:  Narrative Therapy and Sandplay.  I have included a very brief summary of these ways of working below.<p>**Contact and Communication:** I really value your input.  If you notice any changes in your child - either welcome ones or unwelcome - please email with an update or a request for a phone call.<p> One of the benefits of working closely with the school is that I can easily talk with school wellbeing and teaching staff.  This is normally a really good way to receive detailed feedback and set up supports for your child.  However, there may be circumstances where you may decide that you would prefer for this not to happen.  Please indicate your preference on the consent form."
        right = "**First sessions:** One of the primary tasks in counselling is to develop unconditional positive regard - a trusting, open and respectful relationship.  I also want to try to understand the child’s world from their perspective as much as I can.  Often the first session or two will be spent exploring these aims.<p>**Length of support:** I aim to work at the speed that suits your child. Sometimes children only need one group of 5 sessions but other children may need more.  I also offer a follow up service for children who have completed at least one group of 5 sessions and would like to occasionally see me to check in."

    [params.therapy]
    title = "Therapies"
    left = "**Narrative Therapy** is interested in how we create our stories of life.  These are not stories that are ‘made up’ but stories that are based on real life events.  Sometimes people, including children, can get fenced into a particular story line that doesn’t suit them.  Narrative therapists structure conversations in particular ways that help people to notice storylines, talk about their values and intentions for life and ‘rewrite’ story lines that are not helping them.  Narrative Therapy is interested in the existing skills and knowledges of people and how they have helped them in the past and how they could help them in the future.<p>I may send home letters, documents or art works that are based on conversations I have with your child.  I will talk carefully with your child as to how they want to share these letters.  They are not a statement of ‘truth’ or a report to give to a doctor, but are a record of an evolving story.<p>Sometimes these letters may ask for a response.  It is important that these responses are based on your experience of real life events.  If you are unsure about how to respond I am happy to talk with you.  Just send me an email.<p>I have recently completed my Masters degree in Narrative Therapy and Community Work at Melbourne University."
    right = "As an observer of **Sandplay Therapy**, it may appear that your child is simply playing in sand.  This is not so.  The sandtray becomes a setting for people to gain a different or new perspective on a situation.<p>The act of playing in the sand allows the child to ‘sort out’ and make sense of experiences and information. By creating  a scene using symbols (small figurines, toys, ornaments, shells, rocks etc) a child can regain a sense of strength or hope.  The feelings related to the death of  a pet or someone close can be expressed in a sandplay.  Bullying is another common theme in the sandtray.<p>Children are often asked to explain behaviour or verbalise how they feel.  This may be difficult for the child.  They may not know why they behaved in a certain way or how they feel.  Symbols provide a means for expression and exploration in a non-verbal form.<p>Children can unconsciously process an issue by representing it in this way.  Allowing free creation, and working with the ‘story’ can help modify acting-out behaviour. For example, anxieties about school, once expressed through sandplay may be reduced or even resolved.  Generally children will create a sandtray without direction or a theme.<p>Sometimes, a child will ask to take home a photo of a creation they have made.  If your child does this please remember that the child is the person who makes the meaning - for example, a monster may represent feeling powerful for the child, and if an adult labels it as scary or horrible, it can be counter productive.  It is helpful to ask the child to tell you something about it and refrain from your own opinions and comments.  A good start could be : “Would you like to share anything about your sandtray?”  Your child may not wish to share at all and parents are encourage to accept this too."


    [params.contact]
        title = "Contact"
        left = "Email [leanne@riverbankcounselling.com](mailto:leanne@riverbankcounselling.com), or leave a message at the school office for a return phone call."
        right = "Parents can express interest in a group or [complete an intake form](https://docs.google.com/forms/d/e/1FAIpQLSdznalQhN2Yf4anjTjI2IMHbK6H0S7yuOgF2HbwXe_zYvwK5Q/viewform?usp=sf_link) online for individual counselling."

    [params.footer]
        copyright = "(c) Riverbank Counselling, Melbourne, Australia, 2019. ABN: 8278 5160 534"





        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Melbourne, Australia"]

